version: "3.8"

services:
  postgres:
    image: postgres:13.5

    restart: always

    environment:
      - POSTGRES_USER=Bogdan

      - POSTGRES_PASSWORD=hkjfB32ba_0df

    volumes:
      - postgres:/var/lib/postgresql/data

    ports:
      - "4000:5432"

volumes:
  postgres:
